name: Build and deploy Node.js app to Azure Web App - uniq-journey

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".github/**"
      - .env*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install
        run: npm install

      - name: npm build
        run: npm run build
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'uniq-journey'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3E483BBF33C34E9BBF10FCDF73A3C78F }}
